export const allEmployees = [
  {
    id: 1,
    name: "Olivia Rhye",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 5,
    photos: 15,
    initials: "OR",
    lastActivity: "2025-02-20",
  },
  {
    id: 2,
    name: "Phoenix Baker",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 10,
    photos: 20,
    initials: "PB",
    lastActivity: "2025-02-20",
  },
  {
    id: 3,
    name: "Lana Steiner",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 3,
    photos: 13,
    initials: "LS",
    lastActivity: "2025-02-19",
  },
  {
    id: 4,
    name: "Demi Wilkinson",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 6,
    photos: 45,
    initials: "DW",
    lastActivity: "2025-02-20",
  },
  {
    id: 5,
    name: "Candice Wu",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 3,
    photos: 10,
    initials: "CW",
    lastActivity: "2025-02-18",
  },
  {
    id: 6,
    name: "Natali Craig",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 7,
    photos: 50,
    initials: "NC",
    lastActivity: "2025-02-20",
  },
  {
    id: 7,
    name: "Drew Cano",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 6,
    photos: 15,
    initials: "DC",
    lastActivity: "2025-02-19",
  },
  {
    id: 8,
    name: "Andi Lane",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 12,
    photos: 28,
    initials: "AL",
    lastActivity: "2025-02-17",
  },
  {
    id: 9,
    name: "Kate Morrison",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 8,
    photos: 22,
    initials: "KM",
    lastActivity: "2025-02-20",
  },
  {
    id: 10,
    name: "Koray Okumus",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 4,
    photos: 18,
    initials: "KO",
    lastActivity: "2025-02-16",
  },
  {
    id: 11,
    name: "Sienna Hewitt",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 9,
    photos: 35,
    initials: "SH",
    lastActivity: "2025-02-19",
  },
  {
    id: 12,
    name: "Zara Chen",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 15,
    photos: 42,
    initials: "ZC",
    lastActivity: "2025-02-15",
  },
  {
    id: 13,
    name: "Marcus Johnson",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 11,
    photos: 31,
    initials: "MJ",
    lastActivity: "2025-02-18",
  },
  {
    id: 14,
    name: "Sofia Rodriguez",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 7,
    photos: 26,
    initials: "SR",
    lastActivity: "2025-02-20",
  },
  {
    id: 15,
    name: "James Wilson",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 13,
    photos: 38,
    initials: "JW",
    lastActivity: "2025-02-14",
  },
  {
    id: 16,
    name: "Emma Thompson",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 5,
    photos: 19,
    initials: "ET",
    lastActivity: "2025-02-19",
  },
  {
    id: 17,
    name: "Ryan Martinez",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 8,
    photos: 24,
    initials: "RM",
    lastActivity: "2025-02-17",
  },
  {
    id: 18,
    name: "Isabella Garcia",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 14,
    photos: 47,
    initials: "IG",
    lastActivity: "2025-02-13",
  },
  {
    id: 19,
    name: "Noah Davis",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 6,
    photos: 21,
    initials: "ND",
    lastActivity: "2025-02-18",
  },
  {
    id: 20,
    name: "Mia Anderson",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 10,
    photos: 33,
    initials: "MA",
    lastActivity: "2025-02-16",
  },
  {
    id: 21,
    name: "Ethan Taylor",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 9,
    photos: 29,
    initials: "ET",
    lastActivity: "2025-02-19",
  },
  {
    id: 22,
    name: "Ava Brown",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 12,
    photos: 36,
    initials: "AB",
    lastActivity: "2025-02-12",
  },
  {
    id: 23,
    name: "Lucas Miller",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 7,
    photos: 23,
    initials: "LM",
    lastActivity: "2025-02-17",
  },
  {
    id: 24,
    name: "Charlotte Lee",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 11,
    photos: 41,
    initials: "CL",
    lastActivity: "2025-02-15",
  },
  {
    id: 25,
    name: "Mason White",
    avatar: "/placeholder.svg?height=40&width=40",
    customers: 8,
    photos: 27,
    initials: "MW",
    lastActivity: "2025-02-11",
  },
];
export const dateOptions = [
  { label: "All Dates", value: "all" },
  { label: "Today (20-02-2025)", value: "2025-02-20" },
  { label: "Yesterday (19-02-2025)", value: "2025-02-19" },
  { label: "18-02-2025", value: "2025-02-18" },
  { label: "17-02-2025", value: "2025-02-17" },
  { label: "16-02-2025", value: "2025-02-16" },
  { label: "15-02-2025", value: "2025-02-15" },
  { label: "Last Week", value: "week" },
];
export const employeesData = [
  {
    status: true,
    name: "Emma Johnson",
    email: "emma.j@example.com",
    password: "123456",
    phoneNumber: "01123456789",
    branch: "Nasr City",
  },
  {
    status: false,
    name: "Liam Smith",
    email: "liam.s@example.com",
    password: "234567",
    phoneNumber: "01098765432",
    branch: "Zamalek",
  },
  {
    status: true,
    name: "Sophia Williams",
    email: "sophia.w@example.com",
    password: "345678",
    phoneNumber: "01555512345",
    branch: "Mohandseen",
  },
  {
    status: true,
    name: "Noah Brown",
    email: "noah.b@example.com",
    password: "456789",
    phoneNumber: "01234567890",
    branch: "Dokki",
  },
  {
    status: false,
    name: "Isabella Jones",
    email: "isabella.j@example.com",
    password: "567890",
    phoneNumber: "01112223344",
    branch: "Agouza",
  },
  {
    status: true,
    name: "Mason Garcia",
    email: "mason.g@example.com",
    password: "678901",
    phoneNumber: "01020304050",
    branch: "Nasr City",
  },
  {
    status: false,
    name: "Olivia Martinez",
    email: "olivia.m@example.com",
    password: "789012",
    phoneNumber: "01133445566",
    branch: "Zamalek",
  },
  {
    status: true,
    name: "James Wilson",
    email: "james.w@example.com",
    password: "890123",
    phoneNumber: "01055667788",
    branch: "Mohandseen",
  },
  {
    status: true,
    name: "Charlotte Taylor",
    email: "charlotte.t@example.com",
    password: "901234",
    phoneNumber: "01277889900",
    branch: "Dokki",
  },
  {
    status: false,
    name: "Benjamin Anderson",
    email: "benjamin.a@example.com",
    password: "012345",
    phoneNumber: "01100112233",
    branch: "Agouza",
  },
  {
    status: true,
    name: "Amelia Thomas",
    email: "amelia.t@example.com",
    password: "112233",
    phoneNumber: "01044556677",
    branch: "Nasr City",
  },
  {
    status: true,
    name: "William Hernandez",
    email: "william.h@example.com",
    password: "223344",
    phoneNumber: "01588990011",
    branch: "Zamalek",
  },
  {
    status: false,
    name: "Mia Moore",
    email: "mia.m@example.com",
    password: "334455",
    phoneNumber: "01266778899",
    branch: "Mohandseen",
  },
  {
    status: true,
    name: "Elijah Martin",
    email: "elijah.m@example.com",
    password: "445566",
    phoneNumber: "01199001122",
    branch: "Dokki",
  },
  {
    status: true,
    name: "Ava Jackson",
    email: "ava.j@example.com",
    password: "556677",
    phoneNumber: "01022334455",
    branch: "Agouza",
  },
  {
    status: false,
    name: "Alexander Thompson",
    email: "alexander.t@example.com",
    password: "667788",
    phoneNumber: "01155667788",
    branch: "Nasr City",
  },
  {
    status: true,
    name: "Harper White",
    email: "harper.w@example.com",
    password: "778899",
    phoneNumber: "01088990011",
    branch: "Zamalek",
  },
  {
    status: true,
    name: "Michael Lopez",
    email: "michael.l@example.com",
    password: "889900",
    phoneNumber: "01233445566",
    branch: "Mohandseen",
  },
  {
    status: false,
    name: "Evelyn Lee",
    email: "evelyn.l@example.com",
    password: "990011",
    phoneNumber: "01166778899",
    branch: "Dokki",
  },
  {
    status: true,
    name: "Daniel Clark",
    email: "daniel.c@example.com",
    password: "001122",
    phoneNumber: "01099112233",
    branch: "Agouza",
  },
];
export const Photographersata = [
  {
    status: true,
    name: "Emma Johnson",
    branch: "Nasr City",
  },
  {
    status: false,
    name: "Liam Smith",
    branch: "Zamalek",
  },
  {
    status: true,
    name: "Sophia Williams",
    branch: "Mohandseen",
  },
  {
    status: true,
    name: "Noah Brown",
    branch: "Dokki",
  },
  {
    status: false,
    name: "Isabella Jones",
    branch: "Agouza",
  },
  {
    status: true,
    name: "Mason Garcia",
    branch: "Nasr City",
  },
  {
    status: false,
    name: "Olivia Martinez",
    branch: "Zamalek",
  },
  {
    status: true,
    name: "James Wilson",
    branch: "Mohandseen",
  },
  {
    status: true,
    name: "Charlotte Taylor",
    branch: "Dokki",
  },
  {
    status: false,
    name: "Benjamin Anderson",
    branch: "Agouza",
  },
  {
    status: true,
    name: "Amelia Thomas",
    branch: "Nasr City",
  },
  {
    status: true,
    name: "Emma Johnson",
    branch: "Nasr City",
  },
  {
    status: false,
    name: "Liam Smith",
    branch: "Zamalek",
  },
  {
    status: true,
    name: "Sophia Williams",
    branch: "Mohandseen",
  },
  {
    status: true,
    name: "Noah Brown",
    branch: "Dokki",
  },
  {
    status: false,
    name: "Isabella Jones",
    branch: "Agouza",
  },
  {
    status: true,
    name: "Mason Garcia",
    branch: "Nasr City",
  },
  {
    status: false,
    name: "Olivia Martinez",
    branch: "Zamalek",
  },
  {
    status: true,
    name: "James Wilson",
    branch: "Mohandseen",
  },
  {
    status: true,
    name: "Charlotte Taylor",
    branch: "Dokki",
  },
  {
    status: false,
    name: "Benjamin Anderson",
    branch: "Agouza",
  },
  {
    status: true,
    name: "Amelia Thomas",
    branch: "Nasr City",
  },
];
export const currentBranches = [
  {
    status: true,
    name: "Nasr City",
    employees: 5,
    photographers: 15,
    location: "https://www.google.com",
  },
  {
    status: true,
    name: "Zamalek",
    employees: 10,
    photographers: 20,
    location: "https://www.google.com",
  },
  {
    status: false,
    name: "Mohandseen",
    employees: 3,
    photographers: 13,
    location: "https://www.google.com",
  },
  {
    status: true,
    name: "Dokki",
    employees: 6,
    photographers: 45,
    location: "https://www.google.com",
  },
  {
    status: false,
    name: "Agouza",
    employees: 3,
    photographers: 10,
    location: "https://www.google.com",
  },
];
export const packages = [
  {
    status: true,
    name: "5-Photo Package",
    image: "/images/package-icon.png",
    photos: 5,
    price: 250,
    branch: "Nasr City",
    description: "Get 5 printed photos from your event!",
  },
  {
    status: true,
    name: "10-Photo Package",
    image: "/images/package-icon.png",
    photos: 10,
    price: 500,
    branch: "Zamalek",
    description: "Get 10 printed photos from your event!",
  },
  {
    status: false,
    name: "15-Photo Package",
    image: "/images/package-icon.png",
    photos: 15,
    price: 750,
    branch: "Mohandseen",
    description: "Get 15 printed photos from your event!",
  },
];
export const Clients = [
  {
    code: "Olivia Rhye",
    mobileNumber: "Mobile Number",
    receipt: "View Receipt",
    lastActivity: "2025-02-19",
  },
  {
    code: "Olivia Rhye",
    mobileNumber: "Mobile Number",
    receipt: "View Receipt",
    lastActivity: "2025-02-19",
  },
  {
    code: "Olivia Rhye",
    mobileNumber: "Mobile Number",
    receipt: "View Receipt",
    lastActivity: "2025-02-19",
  },
  {
    code: "Olivia Rhye",
    mobileNumber: "Mobile Number",
    receipt: "View Receipt",
    lastActivity: "2025-02-19",
  },
];
